title: "Amina's personal website"
description: "Welcome to my personal website"
author: "Amina Jafarli"
url: "https://aminacafarli787-alt.github.io" # your GitHub Pages URL
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
include:
  - assets
markdown: kramdown






