



baseurl: "" # the subpath of your site, e.g. /blog
url: "https://aminacafarli787-alt.github.io" # the base hostname & protocol for your site, e.g. http://example.com

title: "Amina's personal website"
description: "Welcome to my personal website"

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  
include:
  - assets

markdown: kramdown






